---
title: "data_checking_vl"
format: html
editor: visual
---

set parameters, prepare data

```{r}

vl_indicators <- c("TX_CURR_Lag2", "TX_PVLS_D", "TX_PVLS_N")
 
nonreporters <- c("Ghana", "Liberia", "PNG", "Indonesia", "Vietnam", "Angola")

southern_africa <- c("Lesotho", "Eswatini", "South Africa")


lagged_vl <- check %>% filter(indicator %in% vl_indicators) %>% 
   # bind_rows(vlc_d) %>% 
   filter(!country %in% nonreporters,
          fy == current_fy,
          country %in% southern_africa,
          disagg == "KP" ) %>%
  group_by(country, indicator, funding_agency, keypop) %>%
  summarise(sum.results=sum(cumulative), .groups = "drop") 


```

5a table summarizing VLC and such by country

```{r}
lagged_vl %>%   group_by(country, indicator) %>%
  summarise(sum.results=sum(sum.results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = scales::percent(TX_PVLS_N/TX_PVLS_D, accuracy = 1),
         # vlc =  scales::percent(TX_PVLS_D/TX_CURR_Lag2,accuracy = 1),
         # cohort_vls =  scales::percent(TX_PVLS_N/TX_CURR_Lag2,accuracy = 1)
         )
```

Preparation for 5B

vl by KP and country

```{r}
vl_by_kp_country <- lagged_vl %>%
  select(-funding_agency) %>%
  group_by(country, indicator, keypop) %>%
  summarise(sum.results=sum(sum.results), .groups = "drop") %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2
         )


```

vl by agency and country

```{r}
vl_by_agency_country <- lagged_vl %>%
  group_by(country, indicator, funding_agency) %>%
  summarise(sum.results=sum(sum.results), .groups = "drop") %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2
         )
```

5b

[VL scatter among KP by agency, single country](https://tableau.usaid.gov/views/KeyPopulationsDashboard/5_bVLComparisons/15c0a468-dcb1-4a5c-b0e3-015675f5b342/4c22706e-a79a-49e3-84c4-13ccab479ad7?:display_count=n&:showVizHome=n&:origin=viz_share_link)

by KP, single country

among KP, by country

```{r}


vl_by_agency_country %>% filter(country==southern_africa[1]) %>% 
  ggplot2::ggplot(aes(x=vlc, y=vls, color=funding_agency)) + 
  geom_point(size=3.5) +
  geom_text(aes(label = str_c(scales::percent(vlc, accuracy = 1))), 
            nudge_y = .02) + 
  geom_text(aes(label = str_c(scales::percent(vls, accuracy = 1))), 
            nudge_y = -.02) + 
  ylim(.8,1.2) + xlim(.8,1.2) + 
  si_style_xyline() + 
  theme(legend.position = "bottom", axis.title.x = element_blank()) + 
  scale_color_manual(values = c(
                         USAID = "#002f6c", CDC = "#a7c6ed", 
                        'State Dept.' = "#651d32", Dedup = "#6ca18f", 
                        DOD = "#ba0c2f")) + 
  labs(title = glue(
    "{current_fyq} {southern_africa[1]}, VLC (top label) and VLS (bottom) by agency among KP"
    )) 

vl_by_kp_country %>% filter(country==southern_africa[2]) %>% 
  ggplot2::ggplot(aes(x=vlc, y=vls, color=keypop)) +   geom_point(size=3.5) +
  geom_text(aes(label = str_c(scales::percent(vlc, accuracy = 1))), 
            nudge_y = .005) + 
  geom_text(aes(label = str_c(scales::percent(vls, accuracy = 1))), 
            nudge_y = -.005) + 
  si_style_xyline() + 
  theme(legend.position = "bottom", axis.title.x = element_blank()) + 
  scale_color_manual(values = c(FSW = "#005e7a", MSM = "#f28965", TG = "#990d2e", Prisoners = "#fbcc50", PWID = "#7ecfc0")) + 
  labs(title = glue(
    "{current_fyq} {southern_africa[2]}, VLC (top label) and VLS (bottom) by kp"
    )) 

vl_by_kp_country %>% 
  select(-vlc, -vls) %>%
  group_by(country) %>%
  summarise(TX_PVLS_D = sum(TX_PVLS_D),
            TX_PVLS_N = sum(TX_PVLS_N),
            TX_CURR_Lag2 = sum(coalesce(TX_CURR_Lag2,0)),
            .groups = "drop") %>% 
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2) %>% 
  ggplot2::ggplot(aes(x=vlc, y=vls, group=country)) +   
  # geom_point() +
  geom_text(aes(label = str_c(scales::percent(vlc, accuracy = 1))), 
            nudge_y = .01) + 
  geom_text(aes(label = str_c(scales::percent(vls, accuracy = 1))), 
            nudge_y = -.01) + 
  geom_text(aes(label = country)) +   
  si_style_xyline() + 
  theme(legend.position = "bottom", axis.title.x = element_blank()) + 
  labs(title = glue(
    "{current_fyq} VLC (top label) and VLS (bottom) by country among KP"
    )) 




```

5c,d - Data prep: GP-KP

[VLC](https://tableau.usaid.gov/views/KeyPopulationsDashboard/5_cVLCKP-GP/74c36036-3039-47f1-a215-867ba58308e4/8a6bc501-922c-4002-a454-d63c3fec56d2?:display_count=n&:showVizHome=n&:origin=viz_share_link), [VLS](https://tableau.usaid.gov/views/KeyPopulationsDashboard/5_dVLSKP-GP?:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link) country5

```{r}


vl_gp_kp_pre <- check %>% filter(indicator %in% vl_indicators) %>% 
   bind_rows(vlc_d) %>% 
   mutate(cumulative = coalesce(cumulative,0)) %>%
   filter(!country %in% nonreporters,
          fy == current$fy,
          disagg %in% c("KP", "Total")) %>%
  group_by(country, snu1, disagg, indicator) %>%
  summarise(cumulative=sum(cumulative), .groups = "drop") 

vl_kp <- vl_gp_kp_pre %>% filter(disagg == "KP")
  

vl_gp <- vl_gp_kp_pre %>% 
  mutate(cumulative = if_else(disagg ==  "KP", -cumulative, cumulative)) %>%
  group_by(country, snu1, indicator) %>%
  summarise(cumulative = sum(cumulative), .groups = "drop") %>%
  mutate(disagg = "GP") %>% 
  select(country, snu1, disagg, indicator, cumulative)  


vl_gp_kp <- bind_rows(vl_gp, vl_kp) %>% 
  pivot_wider(values_from = cumulative, names_from = indicator) %>%
  mutate(vlc = TX_PVLS_D/TX_CURR_Lag2,
         vls = TX_PVLS_N/TX_PVLS_D,
         country = fct_reorder(country, desc(country)))
```

VLC GP-KP country5

```{r}

vl_gp_kp2 %>% filter(country == country5) %>%   
  ggplot(aes(y = snu1, x = vlc, color = disagg)) + geom_text(aes(label=scales::percent(vlc, accuracy = 1))) + scale_color_manual(values = c(KP = scooter, GP = grey60k)) + xlim(0,1.1) + labs(
    title = glue(
      "{country5} VLC comparison between KP and GP by SNU, {current_fy}"
    )
      )

vl_gp_kp2 %>% filter(country == country5) %>%
  ggplot(aes(y = snu1, x = vls, color = disagg)) + geom_text(aes(label=scales::percent(vls, accuracy = 1))) + scale_color_manual(values = c(KP = scooter, GP = grey60k)) + labs(
    title = glue(
      "{country5} VLS comparison between KP and GP by SNU, {current_fy}"
    )
      )
```
