---
title: "data_checking_vl"
format: html
editor: visual
---

cascades - ghana, thailand

```{r}
prevention_indicators<- c("KP_PREV","HTS_TST", "HTS_TST_NEG", "PrEP_NEW", "PrEP_CT")
check %>% filter(indicator %in% prevention_indicators,
                  fy == 2022,
                  # funding_agency == "USAID",
                  disagg == "KP",
                  country %in% c("Thailand","Ghana")) %>% 
  select(country, indicator, cumulative) %>%
  group_by(country, indicator) %>%
  summarise(cumulative = sum(cumulative)) %>% print()
```

1a-check ethiopia PrEP_CT

```{r}
qcheck %>% filter(indicator=="PrEP_CT", 
                  fyq == "FY22 Q4",
                  funding_agency == "USAID",
                  disagg == "KP",
                  country=="Ethiopia") %>% 
  select(keypop, results) %>%
  group_by(keypop) %>%
  summarise(results = sum(results)) %>% print()

qcheck %>% filter(indicator=="PrEP_CT", 
                  fyq == "FY22 Q4",
                  disagg == "KP",
                  country=="Ethiopia") %>% 
  select(funding_agency, results) %>%
  group_by(funding_agency) %>%
  summarise(results = sum(results)) %>% print()


#try DR
qcheck %>% filter(indicator=="PrEP_CT", 
                  fyq == "FY22 Q4",
                  funding_agency == "USAID",
                  disagg == "KP",
                  country=="Dominican Republic") %>% 
  select(keypop, results) %>%
  group_by(keypop) %>%
  summarise(results = sum(results)) %>% print()

qcheck %>% filter(indicator=="PrEP_CT", 
                  fyq == "FY22 Q4",
                  disagg == "KP",
                   country=="Dominican Republic") %>% 
  select(funding_agency, results) %>%
  group_by(funding_agency) %>%
  summarise(results = sum(results)) %>% print()
  
  
```

1d - Malawi

```{r}
# 1d ----------------------------------------------------------------------
library(scales)
measure_indicators <- c("TX_PVLS_N", "TX_PVLS_D", "TX_CURR_Lag1", "TX_CURR_Lag2", "HTS_TST_POS", "TX_NEW", "HTS_TST_NEG", "PrEP_NEW")
glimpse(qcheck)
measure_trends_country <- qcheck %>% filter(
  country == "Malawi", disagg == "KP", 
  partner %in% c("CEDEP", "Family Health International", "PAKACHERE INSTITUTE OF HEALTH AND DEVELOPMENT COMMUNICATION"),
  funding_agency == "USAID",
  # psnu %in% c("Cross River", "Niger", "Akwa Ibom"),
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, indicator, partner) %>%
  summarise(sum.results=sum(results)) %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS) %>% print()

#note: no dedup data here, but some dedup data in dashboard


measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, y = linkage, group=partner)) +
  geom_line(aes(color = partner)) +
  geom_label(aes(label = percent(linkage, accuracy = 1))) + ylim(0,1.2)

measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, group=partner)) +
  geom_col(aes(y = HTS_TST_POS), fill = usaid_blue) +
  geom_col(aes(y = TX_NEW), fill = grey50k, width = 0.5) + facet_wrap(~partner)
```

1d - DRC by agency

```{r}


measure_trends_country <- qcheck %>% filter(
  country == "Democratic Republic of the Congo", disagg == "KP", 
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, indicator, funding_agency) %>%
  summarise(sum.results=sum(results)) %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS) %>% print()

#note: no dedup data here, but some dedup data in dashboard


measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, y = linkage, group=funding_agency)) +
  geom_line(aes(color = funding_agency)) +
  geom_label(aes(label = percent(linkage, accuracy = 1))) + ylim(0,1.2)

measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, group=funding_agency)) +
  geom_col(aes(y = HTS_TST_POS), fill = usaid_blue) +
  geom_col(aes(y = TX_NEW), fill = grey50k, width = 0.5) + facet_wrap(~funding_agency)
```

1e - Malawi

```{r}


measure_trends_country <- qcheck %>% filter(
  country == "Malawi", disagg == "KP", 
  funding_agency == "USAID",
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, indicator, snu1) %>%
  summarise(sum.results=sum(results)) %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS) %>% print()

```

2c

```{r}

vl_indicators <- c("TX_PVLS_N", "TX_PVLS_D", "TX_CURR_Lag2")

measure_trends_country <- qcheck %>% filter(
  country %in% c("Cote d'Ivoire", "Malawi"),
  disagg == "KP", 
  funding_agency == "USAID",
  fy == 2022,
  results!=0, indicator %in% vl_indicators) %>%
  group_by(fyq, country, indicator) %>%
  summarise(sum.results=sum(results)) %>% print()
  
  
  
measure_trends_country %>% pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2) %>% print()


measure_trends_country %>% 
  filter(str_detect(indicator, "PVLS"), country == "Cote d'Ivoire") %>%
  ggplot2::ggplot(aes(x = indicator, y=sum.results, fill=indicator)) + geom_col() + geom_text(aes(label = sum.results), position = position_nudge(y=200)) + facet_grid(~fyq)

measure_trends_country %>% 
  filter(str_detect(indicator, "PVLS"), country == "Malawi") %>%
  ggplot2::ggplot(aes(x = indicator, y=sum.results, fill=indicator)) + geom_col() + geom_text(aes(label = sum.results), position = position_nudge(y=200)) + facet_grid(~fyq)
```

5a-b

```{r}
measure_trends_country_sa <- check %>% filter(
  country %in% c("Lesotho", "Eswatini", "South Africa"),
  disagg == "KP", 
  fy == 2022,
  indicator %in% vl_indicators) %>%
  group_by(country, indicator, funding_agency) %>%
  summarise(sum.results=sum(cumulative)) %>% print()

measure_trends_country_plus <- measure_trends_country_sa %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D
         # ,
         # vlc = TX_PVLS_D/TX_CURR_Lag2
         ) %>% print()


measure_trends_country_plus %>% filter(country=="Lesotho") %>% print() %>%
  ggplot2::ggplot(aes(x=vlc, y=vls, fill=funding_agency)) + geom_label(aes(label = scales::percent(vlc, accuracy = 1) )) + ylim(.8,1) + xlim(.8,1)

measure_trends_country_plus %>% filter(country=="Eswatini") %>% print() %>%
  ggplot2::ggplot(aes(x=vlc, y=vls, fill=funding_agency)) + geom_label(aes(label = scales::percent(vls, accuracy = 1) )) 
# + ylim(.8,1) + xlim(.8,1)

measure_trends_country_plus %>% filter(country=="South Africa") %>% print() %>%
  ggplot2::ggplot(aes(x=vlc, y=vls, fill=funding_agency)) + geom_label(aes(label = scales::percent(vls, accuracy = 1) )) 


measure_trends_country_rsa <- check %>% 
  filter(
  country == "South Africa",
  disagg == "KP", 
  # funding_agency == "CDC",
  # partner == "TB HIV CARE ASSOCIATION",
  mech_name == "THCA (GH002189)",
  snu1 %in% c("mp Mpumalanga Province", "kz KwaZulu-Natal Province"),
  fy == 2022,
  # fyq == "FY22 Q4",
  indicator %in% vl_indicators) %>%
  dplyr::group_by(indicator, psnu) %>%
  dplyr::summarise(sum.results=sum(cumulative))

measure_trends_country_plus_rsa <- measure_trends_country_rsa %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D
         # ,
         # vlc = TX_PVLS_D/TX_CURR_Lag2
         )

measure_trends_country_plus_rsa %>% print() 
# %>%
#   ggplot2::ggplot(aes(x=vlc, y=vls, fill=psnu)) + geom_label(aes(label = scales::percent(vls, accuracy = 1) )) 

```

5b deep dive

```{r}
measure_trends_country_rsa <- mer_df %>% 
  filter(
  country == "South Africa",
  str_detect(disaggregate, "Key"), 
  # funding_agency == "CDC",
  # partner == "TB HIV CARE ASSOCIATION",
  mech_name == "THCA (GH002189)",
  snu1 %in% c("mp Mpumalanga Province", "kz KwaZulu-Natal Province"),
  fiscal_year == 2022,
  # fyq == "FY22 Q4",
  indicator == "TX_PVLS") %>%
  dplyr::group_by(indicator, psnu, numeratordenom) %>%
  dplyr::summarise(sum.results=sum(cumulative))

measure_trends_country_plus_rsa <- measure_trends_country_rsa %>% 
  mutate(indicator = str_c(indicator, numeratordenom, sep = "_")) %>% 
  select(-numeratordenom) %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D)

measure_trends_country_plus_rsa %>% print()
```

5c,d - Data prep: GP-KP

```{r}
vl_indicators <- c("TX_CURR_Lag2", "TX_PVLS_D", "TX_PVLS_N")
nonreporters <- c("Ghana", "Liberia", "PNG", "Indonesia", "Vietnam", "Angola")
`%nin%`  <- Negate(`%in%`)

vl_gp_kp <- check %>%
  filter(fy == 2022 ,
         country %nin% nonreporters,
         indicator %in% vl_indicators) %>% 
  group_by(country, snu1, disagg, indicator) %>%
  summarise(results = sum(cumulative), .groups = "drop") %>%
  mutate(indicator = as.character(indicator)) 

vl_kp <- vl_gp_kp %>% filter(disagg == "KP")
  

vl_gp <- vl_gp_kp %>% 
  mutate(results = if_else(disagg ==  "KP", -results, results)) %>%
  group_by(country, snu1, indicator) %>%
  summarise(results = sum(results), .groups = "drop") %>%
  mutate(disagg = "GP") %>% 
  select(country, snu1, disagg, indicator, results)


vl_gp_kp2 <- bind_rows(vl_gp, vl_kp) %>% 
  pivot_wider(values_from = results, names_from = indicator) %>%
  mutate(vlc = TX_PVLS_D/TX_CURR_Lag2,
         vls = TX_PVLS_N/TX_PVLS_D,
         country = fct_reorder(country, desc(country))) %>% print()
```

VLC GP-KP Lesotho

```{r}

vl_gp_kp2 %>% filter(country == "Lesotho") %>%
  ggplot(aes(y = snu1, x = vlc, color = disagg)) + geom_text(aes(label=scales::percent(vlc, accuracy = 1))) + scale_color_manual(values = c(KP = siei_blue, GP = grey60k)) 

vl_gp_kp2 %>% filter(country == "Lesotho") %>%
  ggplot(aes(y = snu1, x = vls, color = disagg)) + geom_text(aes(label=scales::percent(vls, accuracy = 1))) + scale_color_manual(values = c(KP = siei_blue, GP = grey60k)) 
```

```{r}

```

VLS GP-KP

```{r}
vl_gp_kp2 %>% ggplot(aes(y = country, x = vls, color = disagg)) + geom_text(aes(label=scales::percent(vls, accuracy = 1))) + scale_color_manual(values = c(KP = siei_blue, GP = grey60k)) 
```

#6a

```{r}
kp_tx_disagg_indicators <- c("TX_PVLS_N", "TX_PVLS_D", "TX_CURR")

check %>% filter(
  country %in% c("Burma", "Mozambique"),
  disagg == "KP", 
  fy == 2022,
  funding_agency == "USAID",
  indicator %in% kp_tx_disagg_indicators) %>%
  group_by(country, indicator, psnu) %>%
  summarise(sum.results=sum(cumulative)) %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  print()
```

6c - TX_ML

```{r}
check %>% filter(
  country %in% c("Democratic Republic of the Congo"),
  disagg == "KP", 
  fy == 2022,
  funding_agency == "USAID",
  indicator == "TX_ML") %>%
  group_by(country, keypop, tx_ml_reason) %>%
  summarise(sum.results=sum(cumulative)) %>% 
  pivot_wider(values_from = sum.results, names_from = tx_ml_reason) %>%
  print()
```
