---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(patchwork)
library(dplyr)
pick <- function(condition){function(d) d %>% filter_(condition)}
```

2a
```{r, warning=FALSE}
indicators_2a <- c("HTS_TST_POS", "TX_NEW")

measure_trends_2a <- qcheck %>% filter(country == "Botswana", disagg == "KP", results!=0, indicator %in% indicators_2a) %>%
  group_by(fyq, indicator) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>% pivot_longer(cols = HTS_TST_POS:TX_NEW, names_to = "indicator", values_to = "results") %>% na.omit()

measure_trends_2a %>% ggplot2::ggplot(aes(x = fyq, y = results, group = indicator)) + geom_line(aes(color = indicator)) + si_style_xyline() + ylim(0,320)
```

2b
```{r, warning=FALSE}
indicators_2b <- c("TX_CURR","TX_NEW", "TX_NET_NEW")

measure_trends_2b <- qcheck %>% filter(country == "Botswana", disagg == "KP", results!=0, indicator %in% indicators_2b) %>%
  group_by(fyq, indicator) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>% pivot_longer(TX_NEW:TX_NET_NEW, names_to = "indicator", values_to = "results") %>% na.omit()

ggplot(measure_trends_2b, aes(x = fyq, y = results)) + geom_col(data = pick(~indicator == "TX_NEW"), aes(fill = indicator), width = 0.45, position = position_nudge(x = -0.225)) + geom_col(data = pick(~indicator == "TX_NET_NEW"), aes(fill = indicator), width = 0.45, position = position_nudge(x = 0.225)) + geom_line(data = pick(~indicator == "TX_CURR"), (aes(group = 1))) + si_style_xyline()+ scale_color_manual(name = "", values = c("TX_NET_NEW" = grey10k, "TX_NEW" = denim)) + scale_fill_manual(name = "", values = c("TX_NET_NEW" = grey10k, "TX_NEW" = denim))
```

2c: need to add vlc and vls percentages d = vlc n = vls
add separate figure for vlc and vls
```{r, warning=FALSE}
indicators_2c <- c("TX_PVLS_N", "TX_PVLS_D", "TX_CURR_Lag2")

measure_trends_2c<- qcheck %>% filter(country == "Botswana", disagg == "KP", results!=0, indicator %in% indicators_2c) %>%
  group_by(fyq, indicator) %>%
  summarise(sum.results=sum(results), .groups = "drop")  %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vlc = TX_PVLS_D/TX_CURR_Lag2) %>%
  select(fyq, TX_PVLS_N, TX_PVLS_D, vlc, vls) %>%
  pivot_longer(cols = c("TX_PVLS_D","vlc","TX_PVLS_N","vls"), names_to = "indicator", values_to = "results")

c1 <- ggplot(measure_trends_2c, aes(x = fyq, y = results)) + geom_col(data = pick(~indicator == "TX_PVLS_D"), aes(fill = indicator), width = 0.45, position = position_nudge(x = -0.225)) + geom_col(data = pick(~indicator == "TX_PVLS_N"), aes(fill = indicator), width = 0.45, position = position_nudge(x = 0.225)) + si_style_xyline() + scale_color_manual(name = "", values = c("TX_PVLS_N" = grey10k, "TX_PVLS_D" = denim)) + scale_fill_manual(name = "", values = c("TX_PVLS_N" = grey10k, "TX_PVLS_D" = denim))
c2 <- ggplot(measure_trends_2c, aes(x = fyq, y = results)) + geom_line(data = pick(~indicator == "vlc"), aes(fill = indicator)) + geom_line(data = pick(~indicator == "vls"), aes(fill = indicator)) + si_style_xyline()

c1 + c2
```

2d
```{r, warning=FALSE}
indicators_2d <- c("HTS_TST","HTS_TST_POS")

measure_trends_2d <- qcheck %>% filter(country == "India", disagg == "KP", results!=0, indicator %in% indicators_2d) %>%
  group_by(fyq, indicator, keypop) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>% 
  mutate(positivity = HTS_TST_POS/HTS_TST) %>% na.omit()

measure_trends_2d %>% ggplot2::ggplot(aes(x = fyq, y = positivity, group = keypop)) + geom_line(aes(color = keypop)) +  scale_y_continuous(labels = scales::percent) + si_style_xyline() + scale_color_manual(name = "", values = c("FSW" = "#005e7a", "MSM" = "#f28965", "Prisoners" = "#990d2e", "PWID" = "#fbcc50", "TG" = "#7ecfc0", "All People" = "#a7a9ac")) + scale_fill_manual(name = "", values = c("FSW" = "#005e7a", "MSM" = "#f28965", "Prisoners" = "#990d2e", "PWID" = "#fbcc50", "TG" = "#7ecfc0", "All People" = "#a7a9ac"))
```

2e
```{r, warning=FALSE}
coeff <- .00001
indicators_2e <- c("HTS_TST","HTS_TST_POS")

measure_trends_2e<- qcheck %>% filter(country == "Botswana", disagg == "KP", results!=0, indicator %in% indicators_2e) %>%
  group_by(fyq, indicator) %>%
  summarise(sum.results=sum(results), .groups = "drop")  %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(positivity = HTS_TST_POS/HTS_TST)

e1 <- ggplot(measure_trends_2e, aes(x = fyq)) + geom_col(aes(y = HTS_TST_POS)) + si_style_xyline()
e2 <- ggplot(measure_trends_2e, aes(x = fyq)) + geom_line(aes(y = positivity, group = 1)) + si_style_xyline()
e1 + e2
```

2e2
```{r, warning=FALSE}
indicators_2e2 <- c("HTS_TST","HTS_TST_POS")

measure_trends_2e2 <- qcheck %>% filter(country == "India", disagg == "KP", results!=0, indicator %in% indicators_2e) %>%
  group_by(fyq, indicator, keypop) %>%
  summarise(sum.results=sum(results), .groups = "drop")  %>% 
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(positivity = HTS_TST_POS/HTS_TST)

ggplot(measure_trends_2e2, aes(x = fyq, y = HTS_TST_POS, group = keypop)) + geom_line(aes(color = keypop)) + geom_area(aes(fill = keypop)) + scale_color_manual(name = "", values = c("FSW" = "#005e7a", "MSM" = "#f28965", "Prisoners" = "#990d2e", "PWID" = "#fbcc50", "TG" = "#7ecfc0", "All People" = "#a7a9ac")) + scale_fill_manual(name = "", values = c("FSW" = "#005e7a", "MSM" = "#f28965", "Prisoners" = "#990d2e", "PWID" = "#fbcc50", "TG" = "#7ecfc0", "All People" = "#a7a9ac"))
```

2f
```{r, warning=FALSE}
indicators_2f <- c("PrEP_NEW", "PrEP_CT")

measure_trends_2f <- qcheck %>% filter(country == "Malawi", disagg == "KP", results!=0, indicator %in% indicators_2f) %>%
  group_by(fy, fyq, indicator) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>% 
  group_by(fy) %>%
  mutate(fytd = cumsum(PrEP_NEW))

ggplot(measure_trends_2f, aes(x = fyq)) + geom_col(aes(x = fyq, y = fytd, fill = "FY to date")) + geom_col(aes(x = fyq, y = PrEP_NEW, fill = "PrEP_NEW"), width = 0.75) + si_style_xyline() + scale_color_manual(name = "", values = c("FY to date" = grey10k, "PrEP_NEW" = denim)) + scale_fill_manual(name = "", values = c("FY to date" = grey10k, "PrEP_NEW" = denim))
```
