---
title: "data_checking_vl"
format: pdf
editor: visual
---

```{r echo=FALSE}
library(gagglr)
library(scales)
```


1d [Burundi Linkage](https://tableau.usaid.gov/views/KeyPopulationsDashboard/1_dMeasureTrends/2b2f6801-128d-4215-a1a9-115978ce4cbd/94afb7d3-3bbb-4e09-a467-503fc2355ce9)

```{r}
measure_indicators <- c("TX_PVLS_N", "TX_PVLS_D", "TX_CURR_Lag1", "TX_CURR_Lag2", "HTS_TST_POS", "TX_NEW", "HTS_TST_NEG", "PrEP_NEW")

measure_trends_country <- qcheck %>% 
  filter(country == countries[1], disagg == "KP", 
         fyq %in% c("FY22 Q4", "FY23 Q1", "FY23 Q2"),
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, funding_agency, disagg, indicator, partner) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
                  # vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS) %>% print()

#note: no dedup data here, but some dedup data in dashboard


measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, y = linkage, group=partner)) +
  geom_line(aes(color = partner)) +
  geom_text(aes(label = percent(linkage, accuracy = 1))) + ylim(.8,1.5) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)) + si_style_nolines() + labs(title=glue::glue("{measure_trends_country$funding_agency} {measure_trends_country$disagg} linkage by partner"))
  

measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, group=partner)) +
  geom_col(aes(y = HTS_TST_POS), fill = usaid_blue) +
  geom_text(aes(y=HTS_TST_POS*1.2, label=HTS_TST_POS), color=denim) +
  geom_col(aes(y = TX_NEW), fill = grey50k, width = 0.5) + 
  geom_text(aes(y=TX_NEW*0.8, label=TX_NEW), color="black") +
  facet_wrap(~partner) + si_style_nolines() + labs(title=glue::glue("{measure_trends_country$funding_agency} {measure_trends_country$disagg} TX_NEW and HTS_TST_POS by partner"))
```

1d - [Vietnam vls by KP](https://tableau.usaid.gov/views/KeyPopulationsDashboard/1_dMeasureTrends/263772c1-ec12-4cdb-8c2b-099c7a4489d9/094b5cbf-82d2-41d5-b9fb-de825ba7d456)

```{r}


measure_trends_country2 <- qcheck %>% filter(
  country == "Vietnam", disagg == "KP", 
  results!=0, indicator %in% measure_indicators,
  fyq %in% c("FY22 Q4", "FY23 Q1", "FY23 Q2")) %>%
  group_by(fyq, country, indicator, keypop, disagg) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>% 
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         # vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS) %>% print()

#note: no dedup data here, but some dedup data in dashboard

measure_trends_country2 %>% ggplot2::ggplot(aes(x = fyq, y = vls, group=keypop)) +
  geom_line(aes(color = keypop)) +
  geom_text(aes(label = percent(vls, accuracy = 1))) + 
  # ylim(0,1.5) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)) + si_style_nolines() + 
  scale_color_manual(values = c(FSW = "#005e7a", MSM = "#f28965", TG = "#990d2e",
                                Prisoners = "#fbcc50", PWID = "#7ecfc0")) + 
  labs(title=glue::glue("PEPFAR {measure_trends_country2$country}  {measure_trends_country2$disagg} VLS by {measure_trends_country2$disagg}"))
  

measure_trends_country2 %>% ggplot2::ggplot(aes(x = fyq, group=keypop)) +
  geom_col(aes(y = TX_PVLS_D, fill = keypop), ) +
  geom_text(aes(y=TX_PVLS_D*1.2, label=TX_PVLS_D, color=keypop)) +
  geom_col(aes(y = TX_PVLS_N), fill = grey50k, width = 0.5) + 
  geom_text(aes(y=TX_PVLS_N*0.8, label=TX_PVLS_N), color="black") +
  si_style_nolines() + 
  facet_wrap(facets = vars(keypop), nrow=1) +
  scale_color_manual(values = c(FSW = "#005e7a", MSM = "#f28965", TG = "#990d2e",
                                Prisoners = "#fbcc50", PWID = "#7ecfc0")) + 
  labs(title=glue::glue("PEPFAR {measure_trends_country2$country} TX_PVLS N and D by {measure_trends_country2$disagg}"))
```

1e - [linkage](https://tableau.usaid.gov/views/KeyPopulationsDashboard/1_eMeasureComparisons/4e36309b-f0da-4156-94b7-fa96c07278b1/60b22854-8bc3-4aef-b169-b00ceed3f579)

```{r}


measure_by_country <- qcheck %>% filter(
  disagg == "KP", 
  fy == 2023,
  str_extract(fyq, "[1-4]$") == 2 ,
  # funding_agency == "USAID",
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, indicator, disagg) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vls_axis = if_else(vls > 1.05, 1.05, vls),
         #vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS,
         linkage_axis = if_else(linkage > 1.05, 1.05, linkage)) %>% 
  print()

# Define breaks and corresponding colors
breaks <- c(0.84449, 0.94449, 1)
colors <- c( "orange", "gray")

# Assign colors based on breaks
measure_by_country$colors <- cut(measure_by_country$vls_axis, breaks = breaks, labels = colors)

measure_by_country %>% 
  mutate(country = fct_relevel(country, country[order(vls, na.last = TRUE)])) %>%
  arrange(desc(vls)) |> 
  filter(!is.na(vls)) |> 
  slice(c(1:5, (n()-4):n())) %>%
  ggplot(aes(y=country, x=vls_axis)) + geom_col(aes(fill=colors)) + 
  xlab("vls") + xlim(0,1.2) + 
  geom_text(aes(label = scales::percent(vls, accuracy = 1)), position = position_nudge(x=0.06)) + si_style_xyline()  + 
  scale_x_continuous(labels = percent) +
  labs(title=glue::glue("PEPFAR {measure_by_country$disagg} vls by country, {measure_by_country$fyq}")) +
  scale_fill_manual(values = colors) 

```
