---
title: "data_checking_vl"
format: html
editor: visual
---

6a - [VL trends](https://tableau.usaid.gov/views/KeyPopulationsDashboard/2_cVLTrends?:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link)

```{r}
vl_indicators <- c("TX_PVLS_N", "TX_PVLS_D", "TX_CURR_Lag2", "TX_CURR")
countries <- c("Cote d'Ivoire", "Philippines")

pvls_trends_country <- qcheck %>% filter(
  country %in% countries,
  disagg == "KP", 
  fy == 2023,
  results!=0, indicator %in% vl_indicators) %>%
  group_by(fyq, country, disagg, indicator) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>% print()
  
  
  
pvls_trends_country %>% pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         # vlc = TX_PVLS_D/TX_CURR_Lag2
         ) %>% print()


pvls_trends_country %>% 
  filter(str_detect(indicator, "PVLS"), country == countries[1]) %>%
  ggplot2::ggplot(aes(x = indicator, y=sum.results, fill=indicator)) + geom_col() + geom_text(aes(label = sum.results), position = position_nudge(y=200)) + facet_grid(~fyq) +   scale_fill_manual(values = c(TX_CURR = grey10k, TX_PVLS_D = "#64b4a6", TX_PVLS_N = "#004e43")) + si_style_nolines() + theme(axis.text.x = element_text(angle=90), axis.title.x = element_blank(), legend.position = "none") + labs(
    title = glue::glue("PEPFAR {countries[1]} {pvls_trends_country$disagg}")
  )

pvls_trends_country %>% 
  filter(str_detect(indicator, "PVLS"), country == countries[2])  %>%
  ggplot2::ggplot(aes(x = indicator, y=sum.results, fill=indicator)) + geom_col() + geom_text(aes(label = sum.results), position = position_nudge(y=300)) + facet_grid(~fyq) +   scale_fill_manual(values = c(TX_CURR = grey10k, TX_PVLS_D = "#64b4a6", TX_PVLS_N = "#004e43")) + si_style_nolines()  + theme(axis.text.x = element_text(angle=90), axis.title.x = element_blank(), legend.position = "none") + labs(
    title = glue::glue("PEPFAR {countries[2]} {pvls_trends_country$disagg}"))
```

5ab test

```{r}
vl <- check %>% filter(country == "Philippines", disagg == "KP", str_detect(indicator, "PVLS"), fy == 2023) %>%
  group_by(country, disagg, keypop, indicator) %>%
  summarise(sum.cum=sum(cumulative), .groups = "drop") %>%
  pivot_wider(names_from = indicator, values_from = sum.cum) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D) %>%
  print() 
```

set parameters, prepare data

```{r}

vl_indicators <- c("TX_CURR_Lag2", "TX_PVLS_D", "TX_PVLS_N")
 
nonreporters <- c("Ghana", "Liberia", "PNG", "Indonesia", "Vietnam", "Angola")

southern_africa <- c("Zimbabwe", "Lesotho", "South Africa")


lagged_vl_kp <- check %>% filter(indicator %in% vl_indicators) %>% 
   # bind_rows(vlc_d) %>% 
   filter(!country %in% nonreporters,
          fy == current_fy,
          country %in% southern_africa,
          disagg == "KP" ) %>%
  group_by(country, indicator, funding_agency, keypop) %>%
  summarise(sum.results=sum(cumulative), .groups = "drop") %>% print()

lagged_vl_kp %>% count(indicator)



lagged_vl_total <- check %>% filter(indicator %in% vl_indicators) %>% 
   # bind_rows(vlc_d) %>% 
   filter(!country %in% nonreporters,
          fy == current_fy,
          country %in% southern_africa,
          disagg != "KP" ) %>%
  group_by(country, indicator, funding_agency, keypop) %>%
  summarise(sum.results=sum(cumulative), .groups = "drop") %>% print()

lagged_vl_total %>% count(indicator)


```

5abd table summarizing VLC and such by country

#Eswatini CDC numbers are different. All USAID are OK

```{r}
lagged_vl_kp %>%   group_by(country, indicator) %>%
  summarise(sum.results=sum(sum.results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = scales::percent(TX_PVLS_N/TX_PVLS_D, accuracy = 1),
         # vlc =  scales::percent(TX_PVLS_D/TX_CURR_Lag2,accuracy = 1),
         # cohort_vls =  scales::percent(TX_PVLS_N/TX_CURR_Lag2,accuracy = 1)
         )

lagged_vl_kp_neg <- lagged_vl_kp |>  
  group_by(country, indicator, funding_agency) |> 
  summarise(sum.results = -sum(sum.results), .groups = "drop")

lagged_vl_gp <- lagged_vl_total %>%   
  group_by(country, indicator, funding_agency) |> 
  summarise(sum.results=sum(sum.results), .groups = "drop") %>%
    bind_rows(lagged_vl_kp_neg) |> 
        group_by(country, funding_agency, indicator) %>%
        summarise(sum.results=sum(sum.results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = scales::percent(TX_PVLS_N/TX_PVLS_D, accuracy = 1),
         # vlc =  scales::percent(TX_PVLS_D/TX_CURR_Lag2,accuracy = 1),
         # cohort_vls =  scales::percent(TX_PVLS_N/TX_CURR_Lag2,accuracy = 1)
         ) |> print()
```

5C remains non-operational due to removal of "calculations across time" from the MSD at PSNU level
