---
title: "data_checking_vl"
format: pdf
editor: visual
execute: 
  warning: false
---

```{r}
library(tidyverse)
library(gagglr)
```

### 1abcd

clean, used for PREP

```{r, warning=FALSE}
oneA_by_kp <- check %>% filter(
                 disagg == "KP", 
                 # funding_agency == "PEPFAR",
                 fy == max(fy)
                 ) %>%
  group_by(keypop, indicator, fy) %>%
  summarise(sum.cum=sum(cumulative), sum.targets=sum(targets), .groups = "drop") %>%
  mutate(ach = sum.cum/sum.targets) %>%
  filter(sum.cum!=0, 
         indicator=="PrEP_NEW") 
  
oneA_by_kp %>%  ggplot2::ggplot(aes(x = keypop, y = sum.cum, fill=keypop)) + 
  geom_col() + 
  # facet_grid(~ keypop) + 
  geom_text(color = grey90k, position = position_nudge(y=4000), aes(label = scales::percent(ach, accuracy = 1))) +
  geom_text(color = grey10k, position = position_stack(vjust = 0.6), aes(label = sum.cum)) + 
  si_style_nolines() +   theme(legend.position = "none") + xlab("") +
  scale_fill_manual(values = keypop_colors) +
  labs(title = 
         glue::glue("{oneA_by_kp$indicator} achievement by KP, {oneA_by_kp$fy}"))

oneA_by_kp %>% group_by() %>% 
  summarise(sum.cum=sum(sum.cum), sum.targets=sum(sum.targets), .groups = "drop") 

```

### 1cd

clean

```{r}
trends_by_q <- qcheck %>%
  filter(disagg=="KP",
         str_detect(indicator, "PrEP"),
         # country == "Ethiopia",
         funding_agency == "USAID",
         # country %in% c("Uganda", "Tanzania"),
         # fyq %in% c("FY23 Q1", "FY23 Q2", "FY23 Q3", "FY23 Q4")
         ) %>%
  group_by(fyq, disagg, indicator, funding_agency
           # country
           ) %>%
  summarise(results=sum(results),.groups = "drop") 

trends_by_q %>% ggplot(aes(x=fyq, color=indicator)) + 
  geom_line(aes(y=results, group=indicator)) +
  geom_text(aes(y=results*1.1, label=results)) +
  # facet_wrap(~country) +
  theme(panel.background = element_blank(),
        legend.position = "bottom") +
  scale_color_manual(values = c(PrEP_NEW = "#8980cb", PrEP_CT = "#303030")) +
  labs(title=glue::glue("{trends_by_q$disagg} {trends_by_q$funding_agency}  PrEP trends by Q"))
```

### 1a - clean

```{r}
oneA_by_agency <- check %>% filter(funding_agency %in% c("USAID", "CDC"),
                             disagg == "KP", fy == max(fy)) %>%
  group_by(funding_agency, indicator, disagg, fy) %>%
  summarise(sum.cum=sum(cumulative), sum.targets=sum(targets)) %>%
  mutate(ach = sum.cum/sum.targets) %>% 
  filter(sum.cum!=0, indicator %in% c("PrEP_NEW", "PrEP_CT")) 

oneA_by_agency %>%
  ggplot2::ggplot(aes(x = funding_agency, y = sum.cum, fill = funding_agency)) + geom_col() +
  facet_grid(~ indicator) + 
  geom_text(color = grey90k, position = position_nudge(y=20000), aes(label = percent(ach, accuracy = 1))) +
  geom_text(position = position_stack(vjust = 0.6), color = grey10k, 
            size = 3, aes(label = scales::comma(sum.cum))) +
  si_style_nolines() +   scale_fill_manual(values = c(USAID = "#002f6c", CDC = "#a7c6ed", 'State Dept.' = "#651d32", Dedup = "#6ca18f", DOD = "#ba0c2f")) + theme(legend.position = "bottom", axis.title.x = element_blank()) +
  labs(title = glue::glue("Global usaid and CDC achievement by KP, {oneA_by_agency$fy}"))
```

### 1A - Not used this q

```{r}
oneA_by_agency <- check %>% filter(funding_agency %in% c("USAID"),
                                   # country %in% c("Et"),
                             disagg == "KP", fy %in% c(2021, 2022, 2023)) %>%
  group_by(indicator, disagg, fy) %>%
  summarise(sum.cum=sum(cumulative), sum.targets=sum(targets), .groups = "drop") %>%
  mutate(ach = sum.cum/sum.targets) %>% 
  filter(sum.cum!=0, indicator %in% c("HTS_TST_POS")) |> print()
# 
# oneA_by_agency %>%
#   ggplot2::ggplot(aes(x = FY, y = sum.cum)) + geom_col() +
#   facet_grid(~fy ) +
#   geom_text(color = grey90k, position = position_nudge(y=20000), aes(label = percent(ach, accuracy = 1))) +
#   geom_text(position = position_stack(vjust = 0.6), color = grey10k, 
#             size = 3, aes(label = scales::comma(sum.cum))) +
#   si_style_nolines()  +
#   labs(title = glue::glue("Global USAID achievement by KP, {oneA_by_agency$fy}"))
```

### 1b - not done this quarter

```{r}
oneA_by_agency <- check %>% filter(funding_agency %in% c("USAID", "CDC", "Dedup"),
                             disagg == "KP", fy == 2024, country!= "Ukraine") %>%
  group_by(funding_agency, indicator, disagg, fy) %>%
  summarise(sum.cum=sum(cumulative), sum.targets=sum(targets)) %>%
  mutate(ach = sum.cum/sum.targets) %>% 
  filter(sum.cum!=0, indicator %in% c("PrEP_NEW", "HTS_TST_POS", "TX_CURR")) 

oneA_by_agency %>%
  ggplot2::ggplot(aes(x = funding_agency, y = sum.cum, fill = funding_agency)) + geom_col() +
  facet_grid(~ indicator) + 
  geom_text(color = grey90k, position = position_nudge(y=20000), aes(label = percent(ach, accuracy = 1))) +
  geom_text(position = position_stack(vjust = 0.6), color = grey10k, 
            size = 3, aes(label = scales::comma(sum.cum))) +
  si_style_nolines() +   scale_fill_manual(values = c(USAID = "#002f6c", CDC = "#a7c6ed", 'State Dept.' = "#651d32", Dedup = "#6ca18f", DOD = "#ba0c2f")) + theme(legend.position = "bottom", axis.title.x = element_blank()) +
  labs(title = glue::glue("Global PEPFAR achievement by KP, {oneA_by_agency$fy}"))
```

### 1c- clean for USAID, something missing for CDC

```{r}
trends_by_q <- qcheck %>%
  filter(disagg=="KP",
         str_detect(indicator, "PrEP"),
         funding_agency == "USAID",
         # country %in% c("Uganda", "Tanzania"),
         fy >= 2023
         ) %>%
  group_by(fyq, disagg, indicator,
           # country
           ) %>%
  summarise(results=sum(results),.groups = "drop") 

trends_by_q %>% ggplot(aes(x=fyq, color=indicator)) + 
  geom_line(aes(y=results, group=indicator)) +
  geom_text(aes(y=results*1.1, label=results)) +
  # facet_wrap(~country) +
  theme(panel.background = element_blank(),
        legend.position = "bottom") +
  scale_color_manual(values = c(PrEP_NEW = "#8980cb", PrEP_CT = "#303030")) +
  labs(title=glue::glue("{trends_by_q$disagg} PEPFAR PrEP trends by Q"))

```

### 1D - clean for USAID, something missing for CDC

```{r}
trends_by_a <- qcheck %>%
  filter(disagg=="KP",
        indicator=="TX_CURR",
        funding_agency == "USAID",
        # country %in% c("Uganda", "Tanzania"),
         fy >= 2023
         ) %>%
  group_by(fyq, disagg, indicator, keypop,
            # country
           ) %>%
  summarise(results=sum(results),.groups = "drop") 

trends_by_a %>% ggplot(aes(x=fyq, color=keypop)) + 
  geom_line(aes(y=results, group=keypop)) +
  geom_text(aes(y=results*1.1, label=results)) +
  # facet_grid(cols=vars(country)) +
  theme(panel.background = element_blank(),
        legend.position = "bottom") +
   scale_color_manual(values = c(FSW = "#005e7a", MSM = "#f28965", TG = "#7ecfc0", Prisoners = "#990d2e", PWID = "#fbcc50")) +
  labs(title=glue::glue("{trends_by_a$disagg} PEPFAR {trends_by_a$indicator} trends by Q, KP"))
```

### 1e

clean

```{r, warning=FALSE}
measure_indicators <- c("TX_PVLS_N", "TX_PVLS_D", "TX_CURR_Lag1", "TX_CURR_Lag2", "HTS_TST_POS", "TX_NEW", "HTS_TST_NEG", "PrEP_NEW")

measure_trends_country <- qcheck %>% 
  filter(
         country == "Nigeria", 
         disagg == "KP", 
         # fyq %in% c("FY23 Q4", "FY23 Q1", "FY23 Q2", "FY23 Q3"),
  # partner %in% c("CEDEP", "Family Health International", "PAKACHERE INSTITUTE OF HEALTH AND DEVELOPMENT COMMUNICATION"),
  funding_agency == "USAID",
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, funding_agency, disagg, indicator, partner) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
                  # vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS) %>% print()

#note: no dedup data here, but some dedup data in dashboard


measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, y = linkage, group=partner)) +
  geom_line(aes(color = partner)) +
  geom_text(aes(label = scales::percent(linkage, accuracy = 1))) + ylim(.8,1.5) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)) + si_style_nolines() + labs(title=glue::glue("{measure_trends_country$funding_agency} {measure_trends_country$disagg} linkage by partner"))
  

measure_trends_country %>% ggplot2::ggplot(aes(x = fyq, group=partner)) +
  geom_col(aes(y = HTS_TST_POS), fill = usaid_blue) +
  geom_text(aes(y=HTS_TST_POS*1.2, label=HTS_TST_POS), color=denim) +
  geom_col(aes(y = TX_NEW), fill = grey50k, width = 0.5) + 
  geom_text(aes(y=TX_NEW*0.8, label=TX_NEW), color="black") +
  facet_wrap(~partner) + si_style_nolines() + labs(title=glue::glue("{measure_trends_country$funding_agency} {measure_trends_country$disagg} TX_NEW and HTS_TST_POS by partner"))
```

1e - by agency - CLEAN

```{r, warning=FALSE}


measure_trends_country2 <- qcheck %>% filter(
  country == "Nigeria", disagg == "KP", 
  # funding_agency == "USAID",
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, indicator, keypop, disagg) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>% 
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         # vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS) %>% print()

#note: no dedup data here, but some dedup data in dashboard

measure_trends_country2 %>% ggplot2::ggplot(aes(x = fyq, y = linkage, group=keypop)) +
  geom_line(aes(color = keypop)) +
  geom_text(aes(label = scales::percent(linkage, accuracy = 1))) + 
  # ylim(0,1.5) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)) + si_style_nolines() + 
  scale_color_manual(values = keypop_colors) + 
  labs(title=glue::glue("PEPFAR {measure_trends_country2$country}  {measure_trends_country2$disagg} linkage by {measure_trends_country2$disagg}"))
  

measure_trends_country2 %>% ggplot2::ggplot(aes(x = fyq, group=keypop)) +
  geom_col(aes(y = HTS_TST_POS, fill = keypop), ) +
  geom_text(aes(y=HTS_TST_POS*1.2, label=HTS_TST_POS, color=keypop)) +
  geom_col(aes(y = TX_NEW), fill = grey50k, width = 0.5) + 
  geom_text(aes(y=TX_NEW*0.8, label=TX_NEW), color="black") +
  si_style_nolines() + 
  facet_wrap(facets = vars(keypop), nrow=1) +
  scale_fill_manual(values = keypop_colors) + 
  labs(title=glue::glue("PEPFAR {measure_trends_country2$country}HTS_TST_POS AND tx_new by {measure_trends_country2$disagg}"))
```

1f - linkage, vls by country - CLEAN

```{r, warning=false}


measure_by_country <- qcheck %>% filter(
  disagg == "KP", 
  fy >= 2024,
  str_extract(fyq, "[1-4]$") == 1 ,
  # funding_agency == "USAID",
  results!=0, indicator %in% measure_indicators) %>%
  group_by(fyq, country, indicator, disagg) %>%
  summarise(sum.results=sum(results), .groups = "drop") %>%
  pivot_wider(values_from = sum.results, names_from = indicator) %>%
  mutate(vls = TX_PVLS_N/TX_PVLS_D,
         vls_axis = if_else(vls > 1.05, 1.05, vls),
         #vlc = TX_PVLS_D/TX_CURR_Lag2,
         linkage = TX_NEW/HTS_TST_POS,
         linkage_axis = if_else(linkage > 1.05, 1.05, linkage)) %>% 
  print()

# Define breaks and corresponding colors
breaks <- c(.5, 0.84449, 0.94449, 1)
colors <- c("red", "orange", "gray")

# Assign colors based on breaks
measure_by_country$colors <- cut(measure_by_country$linkage_axis, breaks = breaks, labels = colors)

measure_by_country %>% 
  #   mutate(country = fct_reorder(country, (linkage)))  %>%
  #   arrange(desc(linkage)) %>%
  slice(1:5, 15:20) %>%
  ggplot(aes(y=country, x=linkage_axis)) + geom_col(aes(fill=colors)) + 
  xlab("Proxy Linkage") + xlim(0,1.2) + 
  geom_text(aes(label = scales::percent(linkage, accuracy = 1)), position = position_nudge(x=0.06)) + si_style_xyline()  + 
  # scale_x_continuous(labels = percent) +
  labs(title=glue::glue("PEPFAR {measure_by_country$disagg} linkage by country, {measure_by_country$fyq}")) +
  scale_fill_manual(values = colors) 




measure_by_country %>% 
  #   mutate(country = fct_reorder(country, (linkage)))  %>%
  #   arrange(desc(linkage)) %>%
  slice(1:5, 15:20) %>%
  ggplot(aes(y=country, x=vls)) +  
  geom_col(aes(fill=vls)) + 
  xlim(0,1.2) + xlab("VL Suppression") + 
  geom_text(aes(label = scales::percent(vls, accuracy = 1)), position = position_nudge(x=0.06)) + si_style_xyline()  + 
  # scale_x_continuous(labels = percent) +
  labs(title=glue::glue("PEPFAR {measure_by_country$disagg} VLS by country, {measure_by_country$fyq}")) +  
  scale_fill_gradientn(colors = colors, values = scales::rescale(breaks))



```
