---
title: "7ab"
format: html
editor: visual
---

```{r}
country3 <- "Ethiopia"
country4 <- "Vietnam"
country5 <- "Uganda"

fyq_curr <- c("FY24 Q3")

```

### 4a-c

clean - Ukraine data polluting results

```{r}
# country3 <- "Nigeria"
# country4 <- "Vietnam"
# country5 <- "Burundi"

# modality %>%
#   filter(country== country3,indicator %in% c("HTS_TST_POS", "HTS_TST"),
#          str_detect(modality,"SNS"), 
#          fy==2023) %>%
#   select(country, indicator, modality, fyq, results) %>%
#   group_by(country, indicator, modality, fyq) %>% 
#   summarise(results = sum(results), .groups = 'drop') %>%
#   pivot_wider(names_from = indicator, values_from = results) %>%
#   mutate(positivity = scales::percent(HTS_TST_POS/HTS_TST, accuracy = 1)) %>%
#   print()

qcheck %>%
  filter(indicator %in% c("HTS_TST_POS", "HTS_TST"),
        # country== country4,
        disagg == "KP",
        fy == 2024,
        fyq %in% fyq_curr,
        country != "Ukraine"
        ) %>%
  group_by(indicator, funding_agency, fyq) %>% 
  summarise(results = sum(results), .groups = 'drop') %>%
  pivot_wider(names_from = indicator, values_from = results) %>%
  mutate(positivity = scales::percent(HTS_TST_POS/HTS_TST, accuracy = 1)) %>%
  print()

qcheck %>%
  filter(indicator %in% c("HTS_TST_POS", "HTS_TST"),
        fy == 2024,
        fyq %in% fyq_curr,
        country != "Ukraine"
        ) %>%
  group_by(indicator, keypop, fyq) %>% 
  summarise(results = sum(results), .groups = 'drop') %>%
  pivot_wider(names_from = indicator, values_from = results) %>%
  mutate(positivity = scales::percent(HTS_TST_POS/HTS_TST, accuracy = 1)) %>%
  print()
```

### 4d

not checked

```{r}
#| echo: false


modality %>%
  filter(fy == max(fy),
         indicator %in% c("HTS_TST_POS", "HTS_TST"),
        country != "Ukraine"
     ) %>%
  group_by(indicator, modality) %>%
  summarise(results = sum(results), .groups="drop") %>%
  pivot_wider(names_from = indicator, values_from = results) %>%
  mutate(positivity = scales::percent(HTS_TST_POS/HTS_TST, accuracy = 0.1),
         positivity_frac = HTS_TST_POS/HTS_TST) %>%
  arrange(desc(positivity_frac)) %>% select(-positivity_frac) %>%
  print()

qcheck %>%
  filter(indicator %in% c("HTS_TST_POS", "HTS_TST"),
        fy == max(fy),
        disagg == "KP",
        country != "Ukraine") %>%
  group_by(keypop, indicator) %>% 
  summarise(results = sum(results), .groups="drop") %>%
  pivot_wider(names_from = indicator, values_from = results) %>%
  mutate(positivity = scales::percent(HTS_TST_POS/HTS_TST, accuracy = 0.1),
         positivity_frac = HTS_TST_POS/HTS_TST) %>%
  arrange(desc(positivity_frac)) %>% select(-positivity_frac) %>%
  print()
```

### 4ef

clean

```{r}
check %>%
  filter(indicator %in% c("HTS_TST_POS"),
        fy == 2024,
        disagg == "KP",
        country != "Ukraine") %>%
  group_by(keypop) %>% 
  summarise(cumulative = sum(cumulative), targets = sum(targets), 
            .groups="drop") %>%
  mutate(positivity = scales::percent(cumulative/targets, accuracy = 0.1),
         ) %>%
  print()
```
